sudo: required
services:
  - docker

before_install:
  - docker build -t dharaghodasara/react-test -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true dharaghodasara/react-test npm test 

after_success:
  - docker build -t dharaghodasara/multi-client ./client
  - docker build -t dharaghodasara/multi-nginx ./nginx
  - docker build -t dharaghodasara/multi-server ./server
  - docker build -t dharaghodasara/multi-worker ./worker

  
# take those images and put it in docker hub 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push dharaghodasara/multi-client
  - docker push dharaghodasara/multi-nginx
  - docker push dharaghodasara/multi-server
  - docker push dharaghodasara/multi-worker
