sudo: required
services:
  - docker

before_install:
  - docker build -t dharag/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dharag/react-test npm test 

after_success:
  - docker build -t dharag/multi-client ./client
  - docker build -t dharag/multi-nginx ./nginx
  - docker build -t dharag/multi-server ./server
  - docker build -t dharag/multi-worker ./worker

  
# take those images and put it in docker hub 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push dharag/multi-client
  - docker push dharag/multi-nginx
  - docker push dharag/multi-server
  - docker push dharag/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: Multi-Docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-399861883322
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY
